/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.redel_citilink.redelivery_cl;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * MtcTaskPlanned generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`mtc_task_planned`")
public class MtcTaskPlanned implements Serializable {

    private Integer id;
    private Integer docNumber;
    private Integer acId;
    private Integer lastDoneCycle;
    private Integer plannedCycle;
    private Date plannedDate;
    private Integer lifeRemaining;
    private String materialNumber;
    private String equipment;
    private String equipmentDescription;
    private String floc;
    private String serialNumber;
    private String maintenancePlan;
    private Integer vr;
    private Integer prt;
    private String plannedNotification;
    private String lastNotification;
    private String superiorEquipment;
    private String documentRefference;
    private String notificationType;
    private MtcTask mtcTask;
    private Aircraft aircraft;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "\"mtc_task_planned_ID_seq\"" , allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`doc_number`", nullable = true, scale = 0, precision = 10)
    public Integer getDocNumber() {
        return this.docNumber;
    }

    public void setDocNumber(Integer docNumber) {
        this.docNumber = docNumber;
    }

    @Column(name = "`ac_id`", nullable = true, scale = 0, precision = 10)
    public Integer getAcId() {
        return this.acId;
    }

    public void setAcId(Integer acId) {
        this.acId = acId;
    }

    @Column(name = "`last_done_cycle`", nullable = true, scale = 0, precision = 10)
    public Integer getLastDoneCycle() {
        return this.lastDoneCycle;
    }

    public void setLastDoneCycle(Integer lastDoneCycle) {
        this.lastDoneCycle = lastDoneCycle;
    }

    @Column(name = "`planned_cycle`", nullable = true, scale = 0, precision = 10)
    public Integer getPlannedCycle() {
        return this.plannedCycle;
    }

    public void setPlannedCycle(Integer plannedCycle) {
        this.plannedCycle = plannedCycle;
    }

    @Column(name = "`planned_date`", nullable = true)
    public Date getPlannedDate() {
        return this.plannedDate;
    }

    public void setPlannedDate(Date plannedDate) {
        this.plannedDate = plannedDate;
    }

    @Column(name = "`life_remaining`", nullable = true, scale = 0, precision = 10)
    public Integer getLifeRemaining() {
        return this.lifeRemaining;
    }

    public void setLifeRemaining(Integer lifeRemaining) {
        this.lifeRemaining = lifeRemaining;
    }

    @Column(name = "`material_number`", nullable = true, length = 255)
    public String getMaterialNumber() {
        return this.materialNumber;
    }

    public void setMaterialNumber(String materialNumber) {
        this.materialNumber = materialNumber;
    }

    @Column(name = "`equipment`", nullable = true, length = 255)
    public String getEquipment() {
        return this.equipment;
    }

    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    @Column(name = "`equipment_description`", nullable = true, length = 255)
    public String getEquipmentDescription() {
        return this.equipmentDescription;
    }

    public void setEquipmentDescription(String equipmentDescription) {
        this.equipmentDescription = equipmentDescription;
    }

    @Column(name = "`floc`", nullable = true, length = 255)
    public String getFloc() {
        return this.floc;
    }

    public void setFloc(String floc) {
        this.floc = floc;
    }

    @Column(name = "`serial_number`", nullable = true, length = 255)
    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    @Column(name = "`maintenance_plan`", nullable = true, length = 255)
    public String getMaintenancePlan() {
        return this.maintenancePlan;
    }

    public void setMaintenancePlan(String maintenancePlan) {
        this.maintenancePlan = maintenancePlan;
    }

    @Column(name = "`vr`", nullable = true, scale = 0, precision = 10)
    public Integer getVr() {
        return this.vr;
    }

    public void setVr(Integer vr) {
        this.vr = vr;
    }

    @Column(name = "`prt`", nullable = true, scale = 0, precision = 10)
    public Integer getPrt() {
        return this.prt;
    }

    public void setPrt(Integer prt) {
        this.prt = prt;
    }

    @Column(name = "`planned_notification`", nullable = true, length = 255)
    public String getPlannedNotification() {
        return this.plannedNotification;
    }

    public void setPlannedNotification(String plannedNotification) {
        this.plannedNotification = plannedNotification;
    }

    @Column(name = "`last_notification`", nullable = true, length = 255)
    public String getLastNotification() {
        return this.lastNotification;
    }

    public void setLastNotification(String lastNotification) {
        this.lastNotification = lastNotification;
    }

    @Column(name = "`superior_equipment`", nullable = true, length = 255)
    public String getSuperiorEquipment() {
        return this.superiorEquipment;
    }

    public void setSuperiorEquipment(String superiorEquipment) {
        this.superiorEquipment = superiorEquipment;
    }

    @Column(name = "`document_refference`", nullable = true, length = 255)
    public String getDocumentRefference() {
        return this.documentRefference;
    }

    public void setDocumentRefference(String documentRefference) {
        this.documentRefference = documentRefference;
    }

    @Column(name = "`notification_type`", nullable = true, length = 255)
    public String getNotificationType() {
        return this.notificationType;
    }

    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`doc_number`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_mtc_task_planned_TO_meWbVD`"))
    @Fetch(FetchMode.JOIN)
    public MtcTask getMtcTask() {
        return this.mtcTask;
    }

    public void setMtcTask(MtcTask mtcTask) {
        if(mtcTask != null) {
            this.docNumber = mtcTask.getId();
        }

        this.mtcTask = mtcTask;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`ac_id`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_mtc_task_planned_TO_aaB24c`"))
    @Fetch(FetchMode.JOIN)
    public Aircraft getAircraft() {
        return this.aircraft;
    }

    public void setAircraft(Aircraft aircraft) {
        if(aircraft != null) {
            this.acId = aircraft.getId();
        }

        this.aircraft = aircraft;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MtcTaskPlanned)) return false;
        final MtcTaskPlanned mtcTaskPlanned = (MtcTaskPlanned) o;
        return Objects.equals(getId(), mtcTaskPlanned.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}