/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.redel_citilink.redelivery_cl.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.hibernate.Hibernate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.data.util.DaoUtils;
import com.wavemaker.runtime.file.model.Downloadable;

import com.redel_citilink.redelivery_cl.Aircraft;
import com.redel_citilink.redelivery_cl.AircraftUtilization;
import com.redel_citilink.redelivery_cl.MtcTaskPlanned;
import com.redel_citilink.redelivery_cl.RedeliveryCondition;


/**
 * ServiceImpl object for domain model class Aircraft.
 *
 * @see Aircraft
 */
@Service("redelivery_cl.AircraftService")
@Validated
public class AircraftServiceImpl implements AircraftService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AircraftServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("redelivery_cl.MtcTaskPlannedService")
    private MtcTaskPlannedService mtcTaskPlannedService;

    @Lazy
    @Autowired
    @Qualifier("redelivery_cl.RedeliveryConditionService")
    private RedeliveryConditionService redeliveryConditionService;

    @Lazy
    @Autowired
    @Qualifier("redelivery_cl.AircraftUtilizationService")
    private AircraftUtilizationService aircraftUtilizationService;

    @Autowired
    @Qualifier("redelivery_cl.AircraftDao")
    private WMGenericDao<Aircraft, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Aircraft, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "redelivery_clTransactionManager")
    @Override
    public Aircraft create(Aircraft aircraft) {
        LOGGER.debug("Creating a new Aircraft with information: {}", aircraft);

        Aircraft aircraftCreated = this.wmGenericDao.create(aircraft);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(aircraftCreated);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Aircraft getById(Integer aircraftId) {
        LOGGER.debug("Finding Aircraft by id: {}", aircraftId);
        return this.wmGenericDao.findById(aircraftId);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Aircraft findById(Integer aircraftId) {
        LOGGER.debug("Finding Aircraft by id: {}", aircraftId);
        try {
            return this.wmGenericDao.findById(aircraftId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Aircraft found with id: {}", aircraftId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public List<Aircraft> findByMultipleIds(List<Integer> aircraftIds, boolean orderedReturn) {
        LOGGER.debug("Finding Aircrafts by ids: {}", aircraftIds);

        return this.wmGenericDao.findByMultipleIds(aircraftIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "redelivery_clTransactionManager")
    @Override
    public Aircraft update(Aircraft aircraft) {
        LOGGER.debug("Updating Aircraft with information: {}", aircraft);

        List<RedeliveryCondition> redeliveryConditions = aircraft.getRedeliveryConditions();
        List<MtcTaskPlanned> mtcTaskPlanneds = aircraft.getMtcTaskPlanneds();
        List<AircraftUtilization> aircraftUtilizations = aircraft.getAircraftUtilizations();
        if(redeliveryConditions != null && Hibernate.isInitialized(redeliveryConditions)) {
            redeliveryConditions.forEach(_redeliveryCondition -> _redeliveryCondition.setAircraft(aircraft));
        }
        if(mtcTaskPlanneds != null && Hibernate.isInitialized(mtcTaskPlanneds)) {
            mtcTaskPlanneds.forEach(_mtcTaskPlanned -> _mtcTaskPlanned.setAircraft(aircraft));
        }
        if(aircraftUtilizations != null && Hibernate.isInitialized(aircraftUtilizations)) {
            aircraftUtilizations.forEach(_aircraftUtilization -> _aircraftUtilization.setAircraft(aircraft));
        }

        this.wmGenericDao.update(aircraft);
        this.wmGenericDao.refresh(aircraft);

        // Deleting children which are not present in the list.
        if(redeliveryConditions != null && Hibernate.isInitialized(redeliveryConditions) && !redeliveryConditions.isEmpty()) {
            List<RedeliveryCondition> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, RedeliveryCondition.class,
                        new DaoUtils.ChildrenFilter<>("aircraft", aircraft, redeliveryConditions)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_redeliveryCondition -> redeliveryConditionService.delete(_redeliveryCondition));
            aircraft.setRedeliveryConditions(redeliveryConditions);
        }

        // Deleting children which are not present in the list.
        if(mtcTaskPlanneds != null && Hibernate.isInitialized(mtcTaskPlanneds) && !mtcTaskPlanneds.isEmpty()) {
            List<MtcTaskPlanned> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, MtcTaskPlanned.class,
                        new DaoUtils.ChildrenFilter<>("aircraft", aircraft, mtcTaskPlanneds)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_mtcTaskPlanned -> mtcTaskPlannedService.delete(_mtcTaskPlanned));
            aircraft.setMtcTaskPlanneds(mtcTaskPlanneds);
        }

        // Deleting children which are not present in the list.
        if(aircraftUtilizations != null && Hibernate.isInitialized(aircraftUtilizations) && !aircraftUtilizations.isEmpty()) {
            List<AircraftUtilization> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, AircraftUtilization.class,
                        new DaoUtils.ChildrenFilter<>("aircraft", aircraft, aircraftUtilizations)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_aircraftUtilization -> aircraftUtilizationService.delete(_aircraftUtilization));
            aircraft.setAircraftUtilizations(aircraftUtilizations);
        }

        return aircraft;
    }

    @Transactional(value = "redelivery_clTransactionManager")
    @Override
    public Aircraft delete(Integer aircraftId) {
        LOGGER.debug("Deleting Aircraft with id: {}", aircraftId);
        Aircraft deleted = this.wmGenericDao.findById(aircraftId);
        if (deleted == null) {
            LOGGER.debug("No Aircraft found with id: {}", aircraftId);
            throw new EntityNotFoundException(String.valueOf(aircraftId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "redelivery_clTransactionManager")
    @Override
    public void delete(Aircraft aircraft) {
        LOGGER.debug("Deleting Aircraft with {}", aircraft);
        this.wmGenericDao.delete(aircraft);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Page<Aircraft> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Aircrafts");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Page<Aircraft> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Aircrafts");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service redelivery_cl for table Aircraft to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service redelivery_cl for table Aircraft to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Page<RedeliveryCondition> findAssociatedRedeliveryConditions(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated redeliveryConditions");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("aircraft.id = '" + id + "'");

        return redeliveryConditionService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Page<MtcTaskPlanned> findAssociatedMtcTaskPlanneds(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated mtcTaskPlanneds");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("aircraft.id = '" + id + "'");

        return mtcTaskPlannedService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "redelivery_clTransactionManager")
    @Override
    public Page<AircraftUtilization> findAssociatedAircraftUtilizations(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated aircraftUtilizations");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("aircraft.id = '" + id + "'");

        return aircraftUtilizationService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service MtcTaskPlannedService instance
     */
    protected void setMtcTaskPlannedService(MtcTaskPlannedService service) {
        this.mtcTaskPlannedService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service RedeliveryConditionService instance
     */
    protected void setRedeliveryConditionService(RedeliveryConditionService service) {
        this.redeliveryConditionService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service AircraftUtilizationService instance
     */
    protected void setAircraftUtilizationService(AircraftUtilizationService service) {
        this.aircraftUtilizationService = service;
    }

}