/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.redel_citilink.redelga;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * AircraftMtcSchedule generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`aircraft_mtc_schedule`")
public class AircraftMtcSchedule implements Serializable {

    private Integer id;
    private Integer aircraftId;
    private Date lastMtcStart;
    private Date lastMtcEnd;
    private Date nextMtcStart;
    private Date nextMtcEnd;
    private String workPackage;
    private String estCost;
    private String totCost;
    private Aircraft aircraft;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`aircraft_id`", nullable = true, scale = 0, precision = 10)
    public Integer getAircraftId() {
        return this.aircraftId;
    }

    public void setAircraftId(Integer aircraftId) {
        this.aircraftId = aircraftId;
    }

    @Column(name = "`last_mtc_start`", nullable = true)
    public Date getLastMtcStart() {
        return this.lastMtcStart;
    }

    public void setLastMtcStart(Date lastMtcStart) {
        this.lastMtcStart = lastMtcStart;
    }

    @Column(name = "`last_mtc_end`", nullable = true)
    public Date getLastMtcEnd() {
        return this.lastMtcEnd;
    }

    public void setLastMtcEnd(Date lastMtcEnd) {
        this.lastMtcEnd = lastMtcEnd;
    }

    @Column(name = "`next_mtc_start`", nullable = true)
    public Date getNextMtcStart() {
        return this.nextMtcStart;
    }

    public void setNextMtcStart(Date nextMtcStart) {
        this.nextMtcStart = nextMtcStart;
    }

    @Column(name = "`next_mtc_end`", nullable = true)
    public Date getNextMtcEnd() {
        return this.nextMtcEnd;
    }

    public void setNextMtcEnd(Date nextMtcEnd) {
        this.nextMtcEnd = nextMtcEnd;
    }

    @Column(name = "`work_package`", nullable = true, length = 255)
    public String getWorkPackage() {
        return this.workPackage;
    }

    public void setWorkPackage(String workPackage) {
        this.workPackage = workPackage;
    }

    @Column(name = "`est_cost`", nullable = true, length = 255)
    public String getEstCost() {
        return this.estCost;
    }

    public void setEstCost(String estCost) {
        this.estCost = estCost;
    }

    @Column(name = "`tot_cost`", nullable = true, length = 255)
    public String getTotCost() {
        return this.totCost;
    }

    public void setTotCost(String totCost) {
        this.totCost = totCost;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`aircraft_id`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_aircraft_mtc_schedulejPK4b`"))
    @Fetch(FetchMode.JOIN)
    public Aircraft getAircraft() {
        return this.aircraft;
    }

    public void setAircraft(Aircraft aircraft) {
        if(aircraft != null) {
            this.aircraftId = aircraft.getId();
        }

        this.aircraft = aircraft;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AircraftMtcSchedule)) return false;
        final AircraftMtcSchedule aircraftMtcSchedule = (AircraftMtcSchedule) o;
        return Objects.equals(getId(), aircraftMtcSchedule.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}