/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.redel_citilink.redelga;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PostPersist;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * CampTask generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`camp_task`")
public class CampTask implements Serializable {

    private Integer id;
    private String campNumber;
    private String docNumber;
    private String docType;
    private String description;
    private String taskCode;
    private String effectifeAc;
    private String effectifeEng;
    private String thereshold;
    private String interval;
    private String signCodeRefNum;
    private String cat;
    private String campRefference;
    private String rvcd;
    private String campResp;
    private String effectifeDate;
    private String qty;
    private String partNumber;
    private String zone;
    private String access;
    private String manHours;
    private String accessMhTotal;
    private String manHoursTotal;
    private String mpd;
    private List<TaskSchedule> taskSchedules;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`camp_number`", nullable = true, length = 255)
    public String getCampNumber() {
        return this.campNumber;
    }

    public void setCampNumber(String campNumber) {
        this.campNumber = campNumber;
    }

    @Column(name = "`doc_number`", nullable = true, length = 255)
    public String getDocNumber() {
        return this.docNumber;
    }

    public void setDocNumber(String docNumber) {
        this.docNumber = docNumber;
    }

    @Column(name = "`doc_type`", nullable = true, length = 255)
    public String getDocType() {
        return this.docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    @Column(name = "`description`", nullable = true, length = 255)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "`task_code`", nullable = true, length = 255)
    public String getTaskCode() {
        return this.taskCode;
    }

    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    @Column(name = "`effectife_ac`", nullable = true, length = 255)
    public String getEffectifeAc() {
        return this.effectifeAc;
    }

    public void setEffectifeAc(String effectifeAc) {
        this.effectifeAc = effectifeAc;
    }

    @Column(name = "`effectife_eng`", nullable = true, length = 255)
    public String getEffectifeEng() {
        return this.effectifeEng;
    }

    public void setEffectifeEng(String effectifeEng) {
        this.effectifeEng = effectifeEng;
    }

    @Column(name = "`thereshold`", nullable = true, length = 255)
    public String getThereshold() {
        return this.thereshold;
    }

    public void setThereshold(String thereshold) {
        this.thereshold = thereshold;
    }

    @Column(name = "`interval_`", nullable = true, length = 255)
    public String getInterval() {
        return this.interval;
    }

    public void setInterval(String interval) {
        this.interval = interval;
    }

    @Column(name = "`sign_code_ref_num`", nullable = true, length = 255)
    public String getSignCodeRefNum() {
        return this.signCodeRefNum;
    }

    public void setSignCodeRefNum(String signCodeRefNum) {
        this.signCodeRefNum = signCodeRefNum;
    }

    @Column(name = "`cat`", nullable = true, length = 255)
    public String getCat() {
        return this.cat;
    }

    public void setCat(String cat) {
        this.cat = cat;
    }

    @Column(name = "`camp_refference`", nullable = true, length = 255)
    public String getCampRefference() {
        return this.campRefference;
    }

    public void setCampRefference(String campRefference) {
        this.campRefference = campRefference;
    }

    @Column(name = "`rvcd`", nullable = true, length = 255)
    public String getRvcd() {
        return this.rvcd;
    }

    public void setRvcd(String rvcd) {
        this.rvcd = rvcd;
    }

    @Column(name = "`camp_resp`", nullable = true, length = 255)
    public String getCampResp() {
        return this.campResp;
    }

    public void setCampResp(String campResp) {
        this.campResp = campResp;
    }

    @Column(name = "`effectife_date`", nullable = true, length = 255)
    public String getEffectifeDate() {
        return this.effectifeDate;
    }

    public void setEffectifeDate(String effectifeDate) {
        this.effectifeDate = effectifeDate;
    }

    @Column(name = "`qty`", nullable = true, length = 255)
    public String getQty() {
        return this.qty;
    }

    public void setQty(String qty) {
        this.qty = qty;
    }

    @Column(name = "`part_number`", nullable = true, length = 255)
    public String getPartNumber() {
        return this.partNumber;
    }

    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber;
    }

    @Column(name = "`zone_`", nullable = true, length = 255)
    public String getZone() {
        return this.zone;
    }

    public void setZone(String zone) {
        this.zone = zone;
    }

    @Column(name = "`access_`", nullable = true, length = 255)
    public String getAccess() {
        return this.access;
    }

    public void setAccess(String access) {
        this.access = access;
    }

    @Column(name = "`man_hours`", nullable = true, length = 255)
    public String getManHours() {
        return this.manHours;
    }

    public void setManHours(String manHours) {
        this.manHours = manHours;
    }

    @Column(name = "`access_mh_total`", nullable = true, length = 255)
    public String getAccessMhTotal() {
        return this.accessMhTotal;
    }

    public void setAccessMhTotal(String accessMhTotal) {
        this.accessMhTotal = accessMhTotal;
    }

    @Column(name = "`man_hours_total`", nullable = true, length = 255)
    public String getManHoursTotal() {
        return this.manHoursTotal;
    }

    public void setManHoursTotal(String manHoursTotal) {
        this.manHoursTotal = manHoursTotal;
    }

    @Column(name = "`mpd`", nullable = true, length = 255)
    public String getMpd() {
        return this.mpd;
    }

    public void setMpd(String mpd) {
        this.mpd = mpd;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "campTask")
    @Cascade({CascadeType.SAVE_UPDATE})
    public List<TaskSchedule> getTaskSchedules() {
        return this.taskSchedules;
    }

    public void setTaskSchedules(List<TaskSchedule> taskSchedules) {
        this.taskSchedules = taskSchedules;
    }

    @PostPersist
    public void onPostPersist() {
        if(taskSchedules != null) {
            taskSchedules.forEach(_taskSchedule -> _taskSchedule.setCampTask(this));
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CampTask)) return false;
        final CampTask campTask = (CampTask) o;
        return Objects.equals(getId(), campTask.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}