/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.redel_citilink.redelga;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * RedeliveryMatrix generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`redelivery_matrix`")
public class RedeliveryMatrix implements Serializable {

    private Integer id;
    private String component;
    private Integer aircraftId;
    private Integer flightHours;
    private Integer flightCycle;
    private Integer redelFlightHours;
    private Integer redelFlightCycle;
    private Integer mtcFlightHours;
    private Integer mtcFlightCycle;
    private Aircraft aircraft;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`component`", nullable = true, length = 255)
    public String getComponent() {
        return this.component;
    }

    public void setComponent(String component) {
        this.component = component;
    }

    @Column(name = "`aircraft_id`", nullable = true, scale = 0, precision = 10)
    public Integer getAircraftId() {
        return this.aircraftId;
    }

    public void setAircraftId(Integer aircraftId) {
        this.aircraftId = aircraftId;
    }

    @Column(name = "`flight_hours`", nullable = true, scale = 0, precision = 10)
    public Integer getFlightHours() {
        return this.flightHours;
    }

    public void setFlightHours(Integer flightHours) {
        this.flightHours = flightHours;
    }

    @Column(name = "`flight_cycle`", nullable = true, scale = 0, precision = 10)
    public Integer getFlightCycle() {
        return this.flightCycle;
    }

    public void setFlightCycle(Integer flightCycle) {
        this.flightCycle = flightCycle;
    }

    @Column(name = "`redel_flight_hours`", nullable = true, scale = 0, precision = 10)
    public Integer getRedelFlightHours() {
        return this.redelFlightHours;
    }

    public void setRedelFlightHours(Integer redelFlightHours) {
        this.redelFlightHours = redelFlightHours;
    }

    @Column(name = "`redel_flight_cycle`", nullable = true, scale = 0, precision = 10)
    public Integer getRedelFlightCycle() {
        return this.redelFlightCycle;
    }

    public void setRedelFlightCycle(Integer redelFlightCycle) {
        this.redelFlightCycle = redelFlightCycle;
    }

    @Column(name = "`mtc_flight_hours`", nullable = true, scale = 0, precision = 10)
    public Integer getMtcFlightHours() {
        return this.mtcFlightHours;
    }

    public void setMtcFlightHours(Integer mtcFlightHours) {
        this.mtcFlightHours = mtcFlightHours;
    }

    @Column(name = "`mtc_flight_cycle`", nullable = true, scale = 0, precision = 10)
    public Integer getMtcFlightCycle() {
        return this.mtcFlightCycle;
    }

    public void setMtcFlightCycle(Integer mtcFlightCycle) {
        this.mtcFlightCycle = mtcFlightCycle;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`aircraft_id`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_redelivery_matrix_TO_CHVxl`"))
    @Fetch(FetchMode.JOIN)
    public Aircraft getAircraft() {
        return this.aircraft;
    }

    public void setAircraft(Aircraft aircraft) {
        if(aircraft != null) {
            this.aircraftId = aircraft.getId();
        }

        this.aircraft = aircraft;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RedeliveryMatrix)) return false;
        final RedeliveryMatrix redeliveryMatrix = (RedeliveryMatrix) o;
        return Objects.equals(getId(), redeliveryMatrix.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}